import * as types from '../../constants/actionTypes'

export function getData() {
    return {
        type: types.GET_DATA,
        data: [

            {
                "url": "https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?auto=format&fit=crop&w=334&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D",
                "title": "THIS IS SAMPLE TEXT",
                "description": "Sample description goes here",
                "created_at": "24h ago"
            },
            {
                "url": "https://images.unsplash.com/photo-1507537362848-9c7e70b7b5c1?auto=format&fit=crop&w=750&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D",
                "title": "THIS IS SAMPLE TEXT",
                "description": "Sample description goes here",
                "created_at": "24h ago"
            },
            {
                "url": "https://images.unsplash.com/photo-1501159873713-dc65286617cc?auto=format&fit=crop&w=750&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D",
                "title": "THIS IS SAMPLE TEXT",
                "description": "Sample description goes here",
                "created_at": "24h ago"
            },
            {
                "url": "https://images.unsplash.com/photo-1485436442739-c12c6e3673af?auto=format&fit=crop&w=553&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D",
                "title": "THIS IS SAMPLE TEXT",
                "description": "Sample description goes here",
                "created_at": "24h ago"
            },
            {
                "url": "https://images.unsplash.com/photo-1485893226355-9a1c32a0c81e?auto=format&fit=crop&w=500&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D",
                "title": "THIS IS SAMPLE TEXT",
                "description": "Sample description goes here",
                "created_at": "24h ago"
            },
            {
                "url": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=750&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D",
                "title": "THIS IS SAMPLE TEXT",
                "description": "Sample description goes here",
                "created_at": "24h ago"
            },
        ]
    }
}

export function getDataPeople() {
    return {
        type: types.GET_DATA_PEOPLE,
        staff: [
            {
                id: 26,
                name: "Yến Nhi",
                email: "nhi.tty146@gmail.com",
                created_at: "2016-02-10 17:47:17",
                updated_at: "2017-11-27 14:40:16",
                role: 2,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1474537430dcZ400aXFMpPuC0.jpg",
                cover_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1474537492Ia3yzwhkvNhQWz1.jpg",
                description: "Sale & Marketing Manager at colorME",
                university: "ĐH Kinh Tế Quốc Dân",
                work: "colorME",
                address: "Hà Nội",
                username: "nhi.tty146",
                phone: "01689678262",
                how_know: "",
                facebook: "",
                dob: "1995-06-14",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1474537430dcZ400aXFMpPuC0.jpg",
                cover_name: "/images/1474537492Ia3yzwhkvNhQWz1.jpg",
                order: 0,
                role_id: 9,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "e91e63",
                base_id: 3,
                marital: 1,
                homeland: "",
                literacy: 0,
                start_company: "2015-11-01 00:00:00",
                age: 23,
                deleted_at: null,
                type: null
            },
            {
                id: 38,
                name: "Trịnh Thanh Hà",
                email: "trinhthanhha1105@gmail.com",
                created_at: "2016-02-11 03:25:45",
                updated_at: "2017-09-09 17:01:58",
                role: 1,
                code: "",
                avatar_url: "http://s3-ap-southeast-1.amazonaws.com/cmstorage/images/146229259379k739AO8l3Ssyt.jpg",
                cover_url: "",
                description: "chậm lại thôi :v",
                university: "ĐH KTQD",
                work: "",
                address: "Cầu Giấy, Hà Nội",
                username: "trinhthanhha1105",
                phone: "01666575729",
                how_know: "Lý do khác",
                facebook: "",
                dob: "1996-05-11",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/146229259379k739AO8l3Ssyt.jpg",
                cover_name: null,
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "f44336",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 39,
                name: "Hứa Hiền Linh",
                email: "linhhh.bav@gmail.com",
                created_at: "2016-02-11 03:25:46",
                updated_at: "2017-09-28 15:50:40",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1506588638DBPnLTYPoXBHe69.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1460023498BFYRvN18G7rNqhn.jpg",
                description: "",
                university: "Arena Multimedia",
                work: "colorME",
                address: "",
                username: "linhhh.bav",
                phone: "",
                how_know: "",
                facebook: "",
                dob: "2016-08-18",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1506588638DBPnLTYPoXBHe69.jpg",
                cover_name: "/images/1460023498BFYRvN18G7rNqhn.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "e91e63",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 40,
                name: " Đức Hoàng",
                email: "duchoangnguyen240597@gmail.com",
                created_at: "2016-02-11 03:25:48",
                updated_at: "2017-09-09 17:02:10",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1475488476QVYGrKR1hmf3WRu.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1466594740VZrMeFaY923KwkK.jpg",
                description: "",
                university: "",
                work: "",
                address: "",
                username: "duchoangg",
                phone: "",
                how_know: "",
                facebook: "",
                dob: "1997-05-24",
                gender: "1",
                money: 0,
                status: 0,
                avatar_name: "/images/1475488476QVYGrKR1hmf3WRu.jpg",
                cover_name: "/images/1466594740VZrMeFaY923KwkK.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "9c27b0",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 41,
                name: "Con Cá",
                email: "haveyoueverbeenlove@gmail.com",
                created_at: "2016-02-11 03:25:49",
                updated_at: "2017-09-28 01:09:26",
                role: 1,
                code: "",
                avatar_url: "http://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1457529913ZeLnSBzbRoLrCdf.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1462719494tP3UBcZ3obELMH5.jpg",
                description: "",
                university: "",
                work: "",
                address: "",
                username: "concaaa",
                phone: "",
                how_know: "",
                facebook: "",
                dob: "1995-05-13",
                gender: "1",
                money: 814011,
                status: 0,
                avatar_name: "/images/1457529913ZeLnSBzbRoLrCdf.jpg",
                cover_name: "/images/1462719494tP3UBcZ3obELMH5.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "673ab7",
                base_id: 4,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 45,
                name: "Nguyen Mine Linh",
                email: "mailinhnguyen.15@gmail.com",
                created_at: "2016-02-11 03:26:00",
                updated_at: "2017-09-20 15:01:17",
                role: 1,
                code: "",
                avatar_url: "http://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1457424670qC09gEUVo3hAYyb.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1468571054lTj1LM8g1knnWlm.jpg",
                description: "",
                university: "Học viện Công nghệ Bưu chính Viễn thông",
                work: "colorME",
                address: "Tây Hồ Hà Nội",
                username: "mailinhnguyen.15",
                phone: "01654085862",
                how_know: "Lý do khác",
                facebook: "",
                dob: "1996-05-01",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1457424670qC09gEUVo3hAYyb.jpg",
                cover_name: "/images/1468571054lTj1LM8g1knnWlm.jpg",
                order: 0,
                role_id: 20,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "cddc39",
                base_id: 3,
                marital: 1,
                homeland: "Hà Nội",
                literacy: 1,
                start_company: "2016-02-02 00:00:00",
                age: 21,
                deleted_at: null,
                type: null
            },
            {
                id: 46,
                name: "Thu Trang",
                email: "vuthutrang.hmu@gmail.com",
                created_at: "2016-02-11 03:26:03",
                updated_at: "2017-09-09 17:02:27",
                role: 1,
                code: "",
                avatar_url: "http://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1462903003SFggmwF4imwMqTw.jpeg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1470645730OSg0Ela6P3PXYpA.JPG",
                description: "",
                university: "",
                work: "",
                address: "",
                username: "vuthutrang.hmu",
                phone: "",
                how_know: "",
                facebook: "",
                dob: "1997-10-29",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1462903003SFggmwF4imwMqTw.jpeg",
                cover_name: "/images/1470645730OSg0Ela6P3PXYpA.JPG",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "2196f3",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 2,
                name: "Nguyễn Việt Hùng",
                email: "thanghungkhi@gmail.com",
                created_at: "2016-02-11 04:03:36",
                updated_at: "2017-12-02 20:53:43",
                role: 2,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1503369355g3nTaVigDKKyjUQ.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1466096090IsWXNOeHvMIhpMT.jpg",
                description: "",
                university: "FPT University",
                work: "1684026343",
                address: "Dong Da",
                username: "thanghungkhi",
                phone: "01684026343",
                how_know: "",
                facebook: ".",
                dob: "2017-09-14",
                gender: "1",
                money: 1685711000,
                status: 0,
                avatar_name: "/images/1503369355g3nTaVigDKKyjUQ.jpg",
                cover_name: "/images/1466096090IsWXNOeHvMIhpMT.jpg",
                order: 2,
                role_id: 9,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 103,
                color: "009688",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 1,
                name: "Cao Anh Quan",
                email: "aquancva@gmail.com",
                created_at: "2016-02-13 10:35:54",
                updated_at: "2017-11-13 15:42:07",
                role: 2,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1503131612qkfg0K1kNOoQ5IJ.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage",
                description: "",
                university: "Quan Cao Anh",
                work: "0969785925",
                address: "22 Trần Quốc Toản",
                username: "caoquan",
                phone: "0978086530",
                how_know: "",
                facebook: "",
                dob: "2016-12-13",
                gender: "1",
                money: 13,
                status: 0,
                avatar_name: "/images/1503131612qkfg0K1kNOoQ5IJ.jpg",
                cover_name: null,
                order: 0,
                role_id: 9,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 130,
                color: "f44336",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 6730,
                name: "Quan High",
                email: "quan@colorme.vn",
                created_at: "2016-02-13 10:35:54",
                updated_at: "2017-11-13 15:42:07",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1503131612qkfg0K1kNOoQ5IJ.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage",
                description: "",
                university: "Quan Cao Anh",
                work: "0969785925",
                address: "22 Trần Quốc Toản",
                username: "quanca",
                phone: "0978086530",
                how_know: "",
                facebook: "",
                dob: "2016-12-13",
                gender: "1",
                money: 0,
                status: 0,
                avatar_name: "/images/1503131612qkfg0K1kNOoQ5IJ.jpg",
                cover_name: null,
                order: 0,
                role_id: 9,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 130,
                color: "",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 74,
                name: "Phạm Khánh Huyền",
                email: "phamkhanhhuyen.0412@gmail.com",
                created_at: "2016-02-16 16:02:04",
                updated_at: "2017-11-04 21:16:50",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1507718500CG6HuKFWDRE9bEO.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1463560111XoORy9jcgIMytvy.jpg",
                description: "Lêu lêu :) ",
                university: "Đại học Ngoại Thương",
                work: "Công nhân tại ColorME",
                address: "Ba Đình, Hà Nội",
                username: "khanhuyn0412",
                phone: "01699184360",
                how_know: "",
                facebook: "",
                dob: "1996-12-04",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1507718500CG6HuKFWDRE9bEO.jpg",
                cover_name: "/images/1463560111XoORy9jcgIMytvy.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "00bcd4",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 124,
                name: "Nguyễn Anh Đức",
                email: "ducna.mgc@gmail.com",
                created_at: "2016-02-17 20:29:09",
                updated_at: "2017-09-07 10:02:40",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1504753360CgEln48Iw5etz0u.jpg",
                cover_url: "",
                description: "",
                university: "Đại Học Kinh Tế Quốc Dân",
                work: "Đại Học Kinh Tế Quốc Dân",
                address: "Tô Hiệu Cầu Giấy Hà Nội",
                username: "ducna.mgc",
                phone: "0165476269",
                how_know: "Người quen",
                facebook: "https://www.facebook.com/nguyenanh.duc.58",
                dob: "0000-00-00",
                gender: "1",
                money: 0,
                status: 0,
                avatar_name: null,
                cover_name: null,
                order: 0,
                role_id: 8,
                is_request_cv: 0,
                cv_url: "",
                cv_id: 0,
                color: "",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 221,
                name: "Lê Trâm Anh",
                email: "tramanhle9797@gmail.com",
                created_at: "2016-02-22 10:24:03",
                updated_at: "2017-10-10 10:23:22",
                role: 1,
                code: "",
                avatar_url: "http://s3-ap-southeast-1.amazonaws.com/cmstorage/images/146098241539FobW9ObGkNTSp.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1459746168Byul83svmmAwK9A.jpg",
                description: "",
                university: "FTU",
                work: "",
                address: "Hà Đông",
                username: "tramanhle9797",
                phone: "01634361163",
                how_know: "Facebook",
                facebook: "facebook.com/lee.3i",
                dob: "1997-09-07",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/146098241539FobW9ObGkNTSp.jpg",
                cover_name: "/images/1459746168Byul83svmmAwK9A.jpg",
                order: 0,
                role_id: 15,
                is_request_cv: 0,
                cv_url: "",
                cv_id: 0,
                color: "",
                base_id: 0,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 228,
                name: "Dương Nhật Anh",
                email: "anhdnse04260@fpt.edu.vn",
                created_at: "2016-02-22 20:46:43",
                updated_at: "2017-11-30 16:46:28",
                role: 2,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1504404886wdXEVCPFipzhPqJ.jpg",
                cover_url: "",
                description: "",
                university: "FPT University",
                work: "ColorME",
                address: "",
                username: "anhdn_",
                phone: "0934559919",
                how_know: "",
                facebook: "",
                dob: "1995-11-03",
                gender: "1",
                money: 89595000,
                status: 0,
                avatar_name: "/images/1504404886wdXEVCPFipzhPqJ.jpg",
                cover_name: null,
                order: 1,
                role_id: 9,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "",
                base_id: 3,
                marital: 1,
                homeland: "Quảng Trị",
                literacy: 0,
                start_company: "2015-07-07 00:00:00",
                age: 22,
                deleted_at: null,
                type: null
            },
            {
                id: 313,
                name: "Hồ Huyền Trang",
                email: "huyentrang@colorme.vn",
                created_at: "2016-02-28 22:56:05",
                updated_at: "2017-11-05 18:15:20",
                role: 2,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/15045995749eyjJ6XH9OHC43F.jpg",
                cover_url: "",
                description: "",
                university: "Đại học Ngoại Thương",
                work: "",
                address: "185 Chùa Láng Đống Đa, Hà Nội",
                username: "hohuyentrang258",
                phone: "0949587867",
                how_know: "Người quen",
                facebook: "Facebook.com/Sunnyni.7",
                dob: "1997-08-25",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: null,
                cover_name: null,
                order: 0,
                role_id: 18,
                is_request_cv: 0,
                cv_url: "",
                cv_id: 0,
                color: "4caf50",
                base_id: 3,
                marital: 1,
                homeland: "",
                literacy: 1,
                start_company: "2017-02-13 00:00:00",
                age: 20,
                deleted_at: null,
                type: null
            },
            {
                id: 336,
                name: "Nguyễn Kiều Trang",
                email: "kieutrangnt53.fbaelite@gmail.com",
                created_at: "2016-03-02 23:05:46",
                updated_at: "2017-09-09 17:02:52",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1479719670PveTZYk9d4gj7vG.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1465070257fn0YjG9F8kTyRGa.jpg",
                description: "",
                university: "Đại học Ngoại Thương ",
                work: "colorME",
                address: "Chùa Láng ",
                username: "kieutrangnt53.fbaelite",
                phone: "01664202629",
                how_know: "Lý do khác",
                facebook: "https://www.facebook.com/rosalinalaciel",
                dob: "2016-07-06",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1479719670PveTZYk9d4gj7vG.jpg",
                cover_name: "/images/1465070257fn0YjG9F8kTyRGa.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "009688",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 507,
                name: "Le Tuan Dat",
                email: "datlt.bav@gmail.com",
                created_at: "2016-03-21 20:06:27",
                updated_at: "2017-09-09 17:02:57",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1482480963wiOGb5SjVsRb7pT.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1462115910lCup9M2NgCnoOJL.jpg",
                description: "Giảng viên After Effect và Photography tại colorME",
                university: "Học Viện Ngân Hàng",
                work: "ColorME",
                address: "",
                username: "datlt.bav",
                phone: "0975714696",
                how_know: "Lý do khác",
                facebook: "",
                dob: "1996-02-15",
                gender: "1",
                money: 0,
                status: 0,
                avatar_name: "/images/1482480963wiOGb5SjVsRb7pT.jpg",
                cover_name: "/images/1462115910lCup9M2NgCnoOJL.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "4caf50",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 587,
                name: "Nguyễn Ngọc Xuyến",
                email: "thaonguyencass25897@gmail.com",
                created_at: "2016-03-31 17:34:46",
                updated_at: "2017-09-09 17:03:08",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1483364168VmBoUA5pF3RzuWb.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/146565518735Lehcv9q18urPq.jpeg",
                description: "",
                university: "viện đại học mở hà nội",
                work: "",
                address: "tam trinh , hà nội",
                username: "thaonguyencass25897",
                phone: "01662164306",
                how_know: "",
                facebook: "",
                dob: "1996-11-30",
                gender: "2",
                money: 0,
                status: 0,
                avatar_name: "/images/1483364168VmBoUA5pF3RzuWb.jpg",
                cover_name: "/images/146565518735Lehcv9q18urPq.jpeg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "cddc39",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 650,
                name: "Nguyễn Việt Anh",
                email: "nguyenvietanh.020395@gmail.com",
                created_at: "2016-04-08 23:16:51",
                updated_at: "2017-09-09 17:03:13",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1486463354BFNafPVd92tGgaR.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/1466257702CTOXStufY0XoGy1.png",
                description: "Intelligent but lazy",
                university: "Học viện công nghệ Bưu chính viễn thông",
                work: "colorMe",
                address: "102/75 Giải Phóng",
                username: "nguyenvietanh.020395",
                phone: "0902202395",
                how_know: "",
                facebook: "",
                dob: "1995-03-02",
                gender: "1",
                money: 0,
                status: 0,
                avatar_name: "/images/1486463354BFNafPVd92tGgaR.jpg",
                cover_name: "/images/1466257702CTOXStufY0XoGy1.png",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "ffeb3b",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            },
            {
                id: 708,
                name: "Hoàng Minh Tùng ",
                email: "blueberryandmatcha@gmail.com",
                created_at: "2016-04-12 23:05:06",
                updated_at: "2017-10-31 11:31:11",
                role: 1,
                code: "",
                avatar_url: "http://d1j8r0kxyu9tj8.cloudfront.net/images/1505995284sSCsAFCwB0lAf38.jpg",
                cover_url: "https://s3-ap-southeast-1.amazonaws.com/cmstorage/images/146228402001XRjfPETtMCGMj.jpg",
                description: "",
                university: "FPT polytechnic",
                work: "",
                address: "Cầu Diễn, Hà Nội.",
                username: "blueberryandmatcha",
                phone: "0962910248",
                how_know: "Người quen",
                facebook: "https://www.facebook.com/tung.minh.96",
                dob: "0000-00-00",
                gender: "1",
                money: 0,
                status: 2,
                avatar_name: "/images/146228393206v9eV7G9bUb95B.jpg",
                cover_name: "/images/146228402001XRjfPETtMCGMj.jpg",
                order: 0,
                role_id: 10,
                is_request_cv: 1,
                cv_url: "",
                cv_id: 0,
                color: "ffc107",
                base_id: 3,
                marital: 0,
                homeland: "",
                literacy: 0,
                start_company: "0000-00-00 00:00:00",
                age: 0,
                deleted_at: null,
                type: null
            }
        ],
    }
}


export function getDataSchedules() {
    return {
        type: types.GET_DATA_SCHEDULES,
        schedules: [
            {
                id: 24,
                name: "Tối Thứ 2 - Thứ 4 - Thứ 6 (19h00-21h00)",
                description: "",
                sessions_str: "Thứ hai: 19:00-21:00<br/>Thứ tư: 19:00-21:00<br/>Thứ sáu: 19:00-21:00<br/>",
                study_session_ids: [
                    4,
                    9,
                    15
                ]
            },
            {
                id: 22,
                name: "Tối Thứ 3 - Thứ 5 - Thứ 7 (19h00-21h00)",
                description: "",
                sessions_str: "Thứ ba: 19:00-21:00<br/>Thứ năm: 19:00-21:00<br/>Thứ bảy: 19:00-21:00<br/>",
                study_session_ids: [
                    6,
                    12,
                    18
                ]
            },
            {
                id: 21,
                name: "Lịch khoá chuyên sâu 4-6-CN (19h00-21h00)",
                description: "",
                sessions_str: "Thứ tư: 19:00-21:00<br/>Thứ sáu: 19:00-21:00<br/>Chủ nhật: 19:00-21:00<br/>",
                study_session_ids: [
                    9,
                    15,
                    21
                ]
            },
            {
                id: 19,
                name: "Tối Thứ 7 - Chủ Nhật (19h00-21h00)",
                description: "",
                sessions_str: "Thứ bảy: 19:00-21:00<br/>Chủ nhật: 19:00-21:00<br/>",
                study_session_ids: [
                    18,
                    21
                ]
            },
            {
                id: 18,
                name: "Chiều Thứ 7 - Chủ Nhật (15h00-17h00)",
                description: "",
                sessions_str: "Thứ bảy: 15:00-17:00<br/>Chủ nhật: 15:00-17:00<br/>",
                study_session_ids: [
                    17,
                    20
                ]
            },
            {
                id: 17,
                name: "Sáng Thứ 7 - Chủ Nhật (9h00-11h00)",
                description: "",
                sessions_str: "Thứ bảy: 9:00-11:00<br/>Chủ nhật: 9:00-11:00<br/>",
                study_session_ids: [
                    16,
                    19
                ]
            },
            {
                id: 16,
                name: "Tối Thứ 4 - Thứ 6 (19h00-21h00)	",
                description: "",
                sessions_str: "Thứ tư: 19:00-21:00<br/>Thứ sáu: 19:00-21:00<br/>",
                study_session_ids: [
                    9,
                    15
                ]
            },
            {
                id: 15,
                name: "Chiều Thứ 4 - Thứ 6 (15h00-17h00)",
                description: "",
                sessions_str: "Thứ tư: 15:00-17:00<br/>Thứ sáu: 15:00-17:00<br/>",
                study_session_ids: [
                    8,
                    14
                ]
            },
            {
                id: 14,
                name: "Sáng Thứ 4 - Thứ 6 (9h00-11h00)",
                description: "",
                sessions_str: "Thứ tư: 9:00-11:00<br/>Thứ sáu: 9:00-11:00<br/>",
                study_session_ids: [
                    7,
                    13
                ]
            },
            {
                id: 13,
                name: "Tối Thứ 3 - Thứ 5 (19h00-21h00)",
                description: "",
                sessions_str: "Thứ ba: 19:00-21:00<br/>Thứ năm: 19:00-21:00<br/>",
                study_session_ids: [
                    6,
                    12
                ]
            },
            {
                id: 12,
                name: "Chiều Thứ 3 - Thứ 5 (15h00-17h00)",
                description: "",
                sessions_str: "Thứ ba: 15:00-17:00<br/>Thứ năm: 15:00-17:00<br/>",
                study_session_ids: [
                    1,
                    11
                ]
            },
            {
                id: 3,
                name: "Sáng Thứ 3 - Thứ 5 (9h00-11h00)",
                description: "",
                sessions_str: "Thứ ba: 9:00-11:00<br/>Thứ năm: 9:00-11:00<br/>",
                study_session_ids: [
                    5,
                    10
                ]
            }
        ]
    }
}


export function getDataRole() {
    return {
        type: types.GET_DATA_ROLE,
        roles: [
            {
                id: 22,
                role_title: "Designer SM",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 12,
                created_at: "2017-10-22 15:53:12",
                updated_at: "2017-10-22 15:53:12",
                deleted_at: null
            },
            {
                id: 21,
                role_title: "backend",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 9,
                created_at: "2017-10-08 10:35:05",
                updated_at: "2017-11-01 23:33:41",
                deleted_at: null
            },
            {
                id: 20,
                role_title: "Giám đốc đào tạo",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 22,
                created_at: "2017-09-20 15:01:06",
                updated_at: "2017-11-16 00:03:06",
                deleted_at: null
            },
            {
                id: 19,
                role_title: "Sales Manager",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 27,
                created_at: "2017-09-07 14:59:12",
                updated_at: "2017-10-12 13:07:37",
                deleted_at: null
            },
            {
                id: 18,
                role_title: "Trợ lý Giám đốc Sales&Marketing",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 34,
                created_at: "2017-08-08 11:22:05",
                updated_at: "2017-10-12 13:08:19",
                deleted_at: null
            },
            {
                id: 17,
                role_title: "Quản lý sách",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 7,
                created_at: "2016-10-16 10:38:59",
                updated_at: "2016-11-27 00:11:26",
                deleted_at: null
            },
            {
                id: 16,
                role_title: "test chuyen tien",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 1,
                created_at: "2016-08-28 22:09:43",
                updated_at: "2016-08-28 22:09:43",
                deleted_at: null
            },
            {
                id: 15,
                role_title: "Trainee",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 4,
                created_at: "2016-07-11 20:41:32",
                updated_at: "2017-09-05 13:01:59",
                deleted_at: null
            },
            {
                id: 13,
                role_title: "Email Marketing",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 26,
                created_at: "2016-07-08 14:31:05",
                updated_at: "2017-09-05 13:03:42",
                deleted_at: null
            },
            {
                id: 11,
                role_title: "IT",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 48,
                created_at: "2016-07-05 16:36:35",
                updated_at: "2017-10-12 13:10:48",
                deleted_at: null
            },
            {
                id: 10,
                role_title: "Giảng viên",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 12,
                created_at: "2016-07-05 16:35:28",
                updated_at: "2017-09-05 13:01:20",
                deleted_at: null
            },
            {
                id: 9,
                role_title: "CEO",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 61,
                created_at: "2016-07-05 16:34:41",
                updated_at: "2017-10-12 13:09:48",
                deleted_at: null
            },
            {
                id: 8,
                role_title: "Marketing&Sales",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 33,
                created_at: "2016-07-05 16:33:00",
                updated_at: "2017-10-12 13:09:05",
                deleted_at: null
            },
            {
                id: 7,
                role_title: "Telesale",
                role_slug: "",
                num_staffs: 0,
                num_tabs: 21,
                created_at: "2016-07-05 09:40:29",
                updated_at: "2017-04-15 21:50:21",
                deleted_at: null
            }
        ]
    }
}

